import React, { useState } from 'react';
import axios from 'axios';
import BackButton from "./BackButton.js";

export default function GeneratePlaylist(props) {
    const { selectedTracks, selectedArtists, token, handleGoBack } = props;
    const [error, setError] = useState(null);
    let recommendations = [];
    let playlistId = null;


    const getRecommendations = async () => {
        const res = await axios.get(`https://api.spotify.com/v1/recommendations?seed_artists=${selectedArtists}&seed_tracks=${selectedTracks}&limit=30`, {
            headers: {
                Authorization: `Bearer ${token}`
            }
        });
        console.log(res);
        const recommendationURIs = res.data.tracks.map(track => track.uri);
        recommendations = recommendationURIs;
    }

    const createPlaylist = async () => {
        const meRes = await axios.get('https://api.spotify.com/v1/me', {
            headers: {
                'Authorization': `Bearer ${token}`
            }
        });
        const userId = meRes.data.id;
    
        const createPlaylistRes = await axios.post(`https://api.spotify.com/v1/users/${userId}/playlists`, {
            name: "Your New Playlist",
            description: "Generated by BeatBot",
            public: true
        }, {
            headers: {
                'Authorization': `Bearer ${token}`,
                'Content-Type': 'application/json'
            }
        });
        playlistId = createPlaylistRes.data.id
        console.log('Playlist created:', createPlaylistRes.data);
    };    

    const addTracks = async (playlistId) => {
        const res = await axios.post(`https://api.spotify.com/v1/playlists/${playlistId}/tracks`, {
            uris: recommendations
        }, {
            headers: {
                'Authorization': `Bearer ${token}`,
                'Content-Type': 'application/json'
            }
        }
        );

        console.log(res);
    }


    const generatePlaylist = async () => {
        try {
            console.log(token)
            await getRecommendations();
            await createPlaylist();
            console.log(playlistId)
            await addTracks(playlistId);
            console.log("playlist successfully generated")
        } catch (error) {
            if (error.response) {
                console.log(error.response.data);
                console.log(error.response.status);
                console.log(error.response.headers);

                if (error.response.status === 401) {
                    console.error("Error: Unauthorized. Please re-authenticate.");
                    setError("Error: Unauthorized. Please re-authenticate.");
                } else if (error.response.status === 429) {
                    console.error("Error: Too many requests. Please try again later.");
                    setError("Error: Too many requests. Please try again later.");
                } else {
                    console.error("An error occurred, please try again.");
                    setError("An error occurred, please try again.");
                }
            }
        }
    }

    return (
        <div>
            {error && (
                <div>
                    Error: {error}
                </div>
            )}
            <BackButton handleGoBack={handleGoBack} />
            <button onClick={generatePlaylist}>Generate Playlist</button>
        </div >
    )
}